name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: redS2
          owner: xotorg
          base: master
          head: master
